# Docker base image with Python
FROM python:3.9-slim

# Install the necessary Python libraries
RUN pip install --no-cache-dir dotenv

# Copy your Python script into the container
COPY producer/docs_producer.py /app/producer.py